import React, { useState, useEffect, useRef } from 'react';
import { LucideIcon } from './LucideIcon';
import { getPersonalizedAnswer, getStoredHfToken, setStoredHfToken } from '../services/api';

export function AIProcessingPage({ searchQuery, user, learnerProfile, onFinished }) {
  const [currentStep, setCurrentStep] = useState(0);
  const [apiStatus, setApiStatus] = useState("Connecting to backend service...");
  const [apiError, setApiError] = useState(null);
  const [retryCount, setRetryCount] = useState(0);
  const [hfToken, setHfToken] = useState(getStoredHfToken());

  const isFinishedRef = useRef(false);

  useEffect(() => {
    // Stage 1 animation transition
    const t1 = setTimeout(() => setCurrentStep(1), 1200);
    // Stage-2 animation transition
    const t2 = setTimeout(() => setCurrentStep(2), 2400);

    let isMounted = true;
    isFinishedRef.current = false;

    const execute = async () => {
      try {
        setApiError(null);
        setApiStatus("⚡ Connecting to backend service...");

        const results = await getPersonalizedAnswer({
          question: searchQuery,
          age: learnerProfile?.ageGroup || user?.ageGroup || "Adult",
          difficulty: user?.difficulty || "Medium",
          learningStyle: user?.preferredStyles?.[0] || learnerProfile?.learningPreference || "Simple",
          environment: learnerProfile?.environment || "Home",
          onStatus: (statusText) => {
            if (isMounted) setApiStatus(statusText);
          }
        });

        if (!isMounted) return;

        setApiStatus("✨ Answers successfully generated by AI model!");

        if (!isFinishedRef.current) {
          isFinishedRef.current = true;
          onFinished(results);
        }
      } catch (err) {
        if (!isMounted) return;
        console.error("Backend API error:", err);
        setApiError(err.message || "Failed to reach backend service.");
        setApiStatus(`⚠️ ${err.message || "Error generating response"}`);
      }
    };

    execute();

    return () => {
      clearTimeout(t1);
      clearTimeout(t2);
      isMounted = false;
    };
  }, [searchQuery, retryCount]);

  const isZeroGpuError = Boolean(
    apiError && (
      apiError.toLowerCase().includes("zerogpu") ||
      apiError.toLowerCase().includes("quota") ||
      apiError.toLowerCase().includes("runs limit") ||
      apiError.toLowerCase().includes("authenticate with a hugging face token")
    )
  );

  const handleRetry = () => {
    setRetryCount(prev => prev + 1);
  };

  const handleSaveTokenAndRetry = () => {
    setStoredHfToken(hfToken);
    setRetryCount(prev => prev + 1);
  };

  return (
    <div className="w-full max-w-4xl mx-auto py-10 space-y-12 animate-fade-in flex flex-col justify-center min-h-[70vh]">

      {/* Screen Title */}
      <div className="text-center">
        <span className="text-xs font-bold tracking-wider text-brand-400 uppercase">AI Tutoring Pipeline</span>
        <h2 className="text-2xl font-bold text-white mt-1">Generating Explanation for:</h2>
        <div className="text-lg md:text-xl italic font-semibold text-slate-100 mt-2 bg-slate-950/95 w-fit mx-auto px-6 py-2.5 rounded-2xl border border-slate-800 shadow-2xl backdrop-blur-md">
          "{searchQuery}"
        </div>
        <p className="text-xs text-slate-400 mt-3 flex items-center justify-center gap-2">
          {!apiError && (
            <span className="inline-block w-2.5 h-2.5 rounded-full border-2 border-brand-500 border-t-transparent animate-spin"></span>
          )}
          <span>{apiStatus}</span>
        </p>

        {apiError && (
          <div className="bg-slate-950/95 border border-rose-500/40 rounded-3xl p-6 max-w-lg mx-auto text-center space-y-4 mt-4 animate-fade-in shadow-2xl backdrop-blur-md">
            <div className="flex items-center justify-center gap-2 text-rose-300 font-bold text-xs uppercase tracking-wider">
              <LucideIcon name="alert-triangle" className="w-4 h-4 text-rose-400" />
              <span>{isZeroGpuError ? "Hugging Face ZeroGPU Limit" : "AI Generation Error"}</span>
            </div>

            <p className="text-xs text-rose-200/90 leading-relaxed font-medium">
              {apiError}
            </p>

            {isZeroGpuError && (
              <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 space-y-3 text-left">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <span className="text-xs font-bold text-slate-200 block">Why did this happen?</span>
                    <span className="text-[11px] text-slate-400 leading-snug block mt-1">
                      Hugging Face ZeroGPU imposes a temporary free limit on anonymous IP addresses. To unlock higher quota, add your free Hugging Face User Access Token.
                    </span>
                  </div>
                  <a
                    href="https://huggingface.co/settings/tokens"
                    target="_blank"
                    rel="noreferrer"
                    className="text-[11px] text-brand-400 hover:text-brand-300 font-bold underline whitespace-nowrap pt-0.5"
                  >
                    Get Free Token ↗
                  </a>
                </div>

                <div className="flex flex-col sm:flex-row items-center gap-2 pt-1">
                  <input
                    type="password"
                    placeholder="hf_xxxxxxxxxxxxxxxxxxxxxxxxx"
                    value={hfToken}
                    onChange={(e) => setHfToken(e.target.value)}
                    className="w-full sm:flex-1 bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-brand-500 font-mono"
                  />
                  <button
                    type="button"
                    onClick={handleSaveTokenAndRetry}
                    className="w-full sm:w-auto px-4 py-2 bg-brand-600 hover:bg-brand-500 text-white text-xs font-bold rounded-xl transition-all shadow whitespace-nowrap"
                  >
                    Save Token & Retry
                  </button>
                </div>
              </div>
            )}

            <div className="flex items-center justify-center gap-3 pt-1">
              <button
                type="button"
                onClick={handleRetry}
                className="px-4 py-2 bg-brand-600 hover:bg-brand-500 text-white text-xs font-bold rounded-xl transition-all shadow-md"
              >
                Retry AI Call
              </button>
              <button
                type="button"
                onClick={() => onFinished(null)}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium rounded-xl transition-all border border-slate-700"
              >
                Return to Dashboard
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Visual Pipeline Node Progress */}
      <div className="relative">
        {/* Connection line background */}
        <div className="absolute top-1/2 left-4 right-4 h-1 bg-slate-950 border border-slate-900 -translate-y-1/2 z-0 hidden md:block"></div>
        <div
          className="absolute top-1/2 left-4 h-1 bg-brand-500 -translate-y-1/2 z-0 hidden md:block transition-all duration-1000 shadow-sm shadow-brand-500/50"
          style={{ width: `${currentStep === 0 ? '25%' : currentStep === 1 ? '70%' : '100%'}` }}
        ></div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative z-10">

          {/* Node 1: Generate */}
          <div className={`p-6 rounded-3xl bg-slate-950/95 border backdrop-blur-md shadow-2xl transition-all ${currentStep >= 0 ? "border-brand-500 ring-1 ring-brand-500/30" : "border-slate-800"}`}>
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-bold text-brand-400 uppercase tracking-wide">Stage 1</span>
              <span className="text-xs text-slate-400 font-semibold">Generate Pool</span>
            </div>
            <h4 className="font-bold text-white mb-3 flex items-center gap-2">
              <LucideIcon name="cpu" className="w-4 h-4 text-brand-400 animate-spin" />
              Drafting Responses
            </h4>
            <p className="text-xs text-slate-300 leading-normal mb-4">
              LLM builds two raw drafts based on standard educational taxonomy databases.
            </p>

            {/* Response comparison mockup */}
            <div className="grid grid-cols-2 gap-2 text-[10px]">
              <div className={`p-2.5 rounded-xl text-center ${currentStep >= 0 ? "bg-slate-900 border border-slate-800 text-slate-200" : "bg-slate-950 text-slate-600 border border-slate-900"}`}>
                <span className="font-bold block text-[8px] uppercase tracking-wider text-slate-400 mb-1">Response A</span>
                Brief explanation...
              </div>
              <div className={`p-2.5 rounded-xl text-center ${currentStep >= 0 ? "bg-slate-900 border border-slate-800 text-slate-200 animate-pulse" : "bg-slate-950 text-slate-600 border border-slate-900"}`}>
                <span className="font-bold block text-[8px] uppercase tracking-wider text-slate-400 mb-1">Response B</span>
                Detailed explanation...
              </div>
            </div>
          </div>

          {/* Node 2: Compare */}
          <div className={`p-6 rounded-3xl bg-slate-950/95 border backdrop-blur-md shadow-2xl transition-all ${currentStep >= 1 ? "border-brand-500 ring-1 ring-brand-500/30 opacity-100" : "border-slate-800/80 opacity-75"}`}>
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-bold text-brand-400 uppercase tracking-wide">Stage 2</span>
              <span className="text-xs text-slate-400 font-semibold">Evaluate Pool</span>
            </div>
            <h4 className="font-bold text-white mb-3 flex items-center gap-2">
              <LucideIcon name="check-square" className={`w-4 h-4 ${currentStep >= 1 ? "text-emerald-400" : "text-slate-500"}`} />
              AI Response Evaluator
            </h4>
            <p className="text-xs text-slate-300 leading-normal mb-3">
              Comparing responses for accuracy, clarity, and relevance to profiles.
            </p>

            <div className="space-y-1.5 text-[9px] font-semibold">
              <div className="flex items-center gap-2 text-emerald-400">
                <span>✓</span>
                <span>Accuracy Check Passed</span>
              </div>
              {currentStep >= 1 ? (
                <>
                  <div className="flex items-center gap-2 text-emerald-400">
                    <span>✓</span>
                    <span>Relevance Match: 98%</span>
                  </div>
                  <div className="text-[10px] text-brand-300 font-bold mt-2 bg-brand-500/10 py-1 px-2 rounded-lg w-fit border border-brand-500/20">
                    Best response selected
                  </div>
                </>
              ) : (
                <div className="text-slate-500 flex items-center gap-2">
                  <span className="inline-block w-1.5 h-1.5 rounded-full bg-slate-700"></span>
                  <span>Analyzing style preferences...</span>
                </div>
              )}
            </div>
          </div>

          {/* Node 3: Personalize */}
          <div className={`p-6 rounded-3xl bg-slate-950/95 border backdrop-blur-md shadow-2xl transition-all ${currentStep >= 2 ? "border-brand-500 ring-1 ring-brand-500/30 opacity-100" : "border-slate-800/80 opacity-75"}`}>
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-bold text-brand-400 uppercase tracking-wide">Stage 3</span>
              <span className="text-xs text-slate-400 font-semibold">Translate Styles</span>
            </div>
            <h4 className="font-bold text-white mb-3 flex items-center gap-2">
              <LucideIcon name="sparkles" className={`w-4 h-4 ${currentStep >= 2 ? "text-brand-400 animate-pulse" : "text-slate-500"}`} />
              Personalizing for you
            </h4>
            <p className="text-xs text-slate-300 leading-normal mb-3">
              Adapting the selected explanation text to your active dashboard preference parameters.
            </p>

            <div className="space-y-1 text-[9px] text-slate-300">
              <div className="flex items-center justify-between border-b border-slate-850 pb-1">
                <span className="text-slate-400">Target Level:</span>
                <span className="text-brand-400 font-bold">{user.learningLevel}</span>
              </div>
              <div className="flex items-center justify-between border-b border-slate-850 pb-1">
                <span className="text-slate-400">Age Tone:</span>
                <span className="text-brand-400 font-bold">{user.ageGroup}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-slate-400">Styles:</span>
                <span className="text-brand-400 font-bold truncate max-w-[120px]">{user.preferredStyles.join(", ")}</span>
              </div>
            </div>
          </div>

        </div>
      </div>

      {/* Progress status loader bars */}
      <div className="w-full max-w-sm mx-auto bg-slate-950/95 border border-slate-800 p-5 rounded-3xl shadow-2xl backdrop-blur-md">
        <div className="flex items-center justify-between text-xs font-semibold text-slate-300 mb-2">
          <span>Overall Compile State</span>
          <span className="text-brand-400 font-bold">{currentStep === 0 ? "35%" : currentStep === 1 ? "75%" : "99%"}</span>
        </div>
        <div className="w-full bg-slate-900 border border-slate-800/60 h-2 rounded-full overflow-hidden">
          <div
            className="bg-brand-500 h-full rounded-full transition-all duration-1000 shadow-sm shadow-brand-500/50"
            style={{ width: `${currentStep === 0 ? '35%' : currentStep === 1 ? '75%' : '99%'}` }}
          ></div>
        </div>
      </div>

    </div>
  );
}

export default AIProcessingPage;
